name: satphoto
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - opencv
  - matplotlib
  - tifffile
  - pandas
  - rasterio
  - gdal
  - pillow
  - onnxruntime
  - python-docx
  - pyqt=5.15
  - pip
  - pip:
      - pygeodesy
